#ifndef FUNCIONES_H_INCLUDED
#define FUNCIONES_H_INCLUDED
#include "ClassAuto.h"
#include "ClassCabezeraVenta.h"
#include "ClassAuto.h"
#include "ClassCabezeraVenta.h"
#include "ClassClientes.h"
#include "ClassVendedores.h"
#include "ClassDetalleVenta.h"
void menu();
void iniciarSesion();
void registrarse();
void menuVendedores();
void ventaVehiculo();
void recuperarClave();
int nuevoId();
void generarFactura();
void informacionClientes();
void LH();
void LH2();
void informacionClientes();
void listarClientesOrdenados();
void listarClientesOrdenados();
void informacionFacturas();
void buscarFacturas();
void recaudaciones();
void recaudacioTotal();
void recaudacionXmes();

#endif // FUNCIONES_H_INCLUDED
